# ==========================
# 1. Dependencias
# ==========================
FROM node:21-alpine3.19 AS deps
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci  

# ==========================
# 2. Build
# ==========================
FROM node:21-alpine3.19 AS build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

# 🚨 Copiamos primero package.json y prisma para no romper el cache
COPY package*.json ./ 
COPY prisma ./prisma

# Ahora copiamos el resto del código
COPY . .

RUN npm run build

# producción sin devDependencies
RUN npm ci -f --only=production && npm cache clean --force

RUN npx prisma generate

# ==========================
# 3. Producción
# ==========================
FROM node:21-alpine3.19 AS prod
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma

# dar permisos a node
RUN chown -R node:node /usr/src/app/prisma


ENV NODE_ENV=production
USER node
EXPOSE 3000

CMD ["node", "dist/main.js"]
